VendingMachine: VDMachine.VendingMachineFrame Class Reference
VDMachine.VendingMachineFrame Class Reference
Classes
class BoxLabel
class ButtonPanel
class TitlePanel
class VendingMachinePanel
Public Member Functions
VendingMachineFrame ()
Static Public Member Functions
static void main (String[] args)
Detailed Description
VendingMachineFrame과 VendingMachine을 하나로 합쳤기 때문에 VendingMachine클래스는 따로 만들지 않음
Parameters
VendingMachineProgram 자판기 시뮬레이션 패널
product 제품의 갯수가 여러개이므로 List를 사용
change 거스름돈 반환기능을 포함
money 사용자가 투입하는 돈
MAXSIZE 통의 크기이자 각 제품의 최대 갯수를 15로 설정
MAXCOIN 자판기 안에 들어있는 동전의 갯수를 50으로 초기화
Definition at line 23 of file VendingMachineFrame.java.
Constructor & Destructor Documentation
VDMachine.VendingMachineFrame.VendingMachineFrame ()
프레임 설정
Definition at line 34 of file VendingMachineFrame.java.
References VDMachine.Change.insert, VDMachine.Change.InsertCoin(), VDMachine.Change.Payback(), VDMachine.Product.setnumOfPurchase(), and VDMachine.Product.setnumOfStock().
Referenced by VDMachine.VendingMachineFrame.main().
{
         setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
         VendingMachinePanel = new VendingMachinePanel();
         add(new TitlePanel(), BorderLayout.NORTH);
         add(VendingMachinePanel, BorderLayout.CENTER);
         add(new ButtonPanel(), BorderLayout.SOUTH);
         setSize(850,800);
         setResizable(false); // 사용자가 프레임의 크기 조절할 수 없도록 설정
         setVisible(true);
     }
Member Function Documentation
static void VDMachine.VendingMachineFrame.main (String [] args) static
Definition at line 481 of file VendingMachineFrame.java.
References VDMachine.VendingMachineFrame.VendingMachineFrame().
{
         new VendingMachineFrame();
     }
The documentation for this class was generated from the following file:
C:/pub/workspace/VendingMachine/src/VDMachine/VendingMachineFrame.java